---
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/nicholaswilde/helm-charts/tree/main/charts/common/values.yaml
#

image:
  repository: ghcr.io/linuxserver/hedgedoc
  pullPolicy: IfNotPresent
  tag: "version-1.9.0"

secret:
  DB_PASS: ""

# See more environment variables in the hedgedoc documentation
# https://github.com/linuxserver/docker-hedgedoc#parameters
env: 
  TZ: "Asia/Tokyo"
  CMD_DOMAIN: "hd.soine.site"
  PUID: "1000"
  PGID: "1000"
  CMD_DB_USERNAME: "hedgedoc"
  CMD_DB_HOST: "galera-mariadb-galera.default.svc.cluster.local"
  CMD_DB_NAME: "hedgedoc"
  CMD_DB_PORT: "3306"
  CMD_LDAP_URL: ""
  CMD_LDAP_BINDDN: ""
  CMD_PROTOCOL_USESSL: "true"
  CMD_LDAP_BINDCREDENTIALS: ""
  CMD_LDAP_SEARCHBASE: ""
  CMD_LDAP_SEARCHFILTER: ""
  CMD_LDAP_USERIDFIELD: "uid"
  CMD_LDAP_USERNAMEFIELD: "uid"
  CMD_LOGLEVEL: "debug"
  CMD_ALLOW_ORIGIN: "['hd.soine.site', 'localhost']"
  CMD_EMAIL: "false"
  CMD_ALLOW_EMAIL_REGISTER: "false"

  # CMD_CSP_ENABLE: "false"

service:
  port:
    port: 3000

ingress:
  enabled: false

persistence:
  config:
    enabled: false
    emptyDir: false
    mountPath: /config

# Enable mariadb
# https://github.com/nicholaswilde/helm-charts/blob/main/charts/mariadb/values.yaml
mariadb:
  enabled: false
  secret:
    MYSQL_ROOT_PASSWORD: hedgedoc-pass
    MYSQL_PASSWORD: hedgedoc-pass
  env:
    MYSQL_USER: hedgedoc
    MYSQL_DATABASE: hedgedoc
  fullnameOverride: template-mariadb
