apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: misskey-yude-jp-files-pvc
  namespace: misskey-yude-jp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
