apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
        - name: caddy
          image: caddy:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: caddy-data
              mountPath: /data
            - name: caddy-config
              mountPath: /etc/caddy
      volumes:
        - name: caddy-data
          emptyDir: {}
        - name: caddy-config
          configMap:
            name: caddy-config