apiVersion: apps/v1
kind: Deployment
metadata:
  name: wbo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wbo
  template:
    metadata:
      labels:
        app: wbo
    spec:
      containers:
      - name: wbo
        image: lovasoa/wbo
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /opt/app/server-data
      volumes:
        - name: data
          hostPath:
              path: /mnt/k3s-pvc/wbo
---
apiVersion: v1
kind: Service
metadata:
  name: wbo
spec:
  selector:
    app: wbo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http