kind: ConfigMap
apiVersion: v1
metadata:
  name: env
  namespace: miniflux
data:
  DATABASE_URL: "postgres://miniflux:password@main-rw.cnpg-system.svc.cluster.local?sslmode=disable"
  RUN_MIGRATIONS: "1"
  CREATE_ADMIN: "1"
  ADMIN_USERNAME: "admin"
  ADMIN_PASSWORD: "admin123"
  POCKET_CONSUMER_KEY: ""
  