apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    tier: sidekiq
  name: sidekiq
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        tier: sidekiq
    spec:
      initContainers:
        - name: db-migrate
          image: tootsuite/mastodon:v4.2.10
          command: 
            - /bin/bash
            - -c
            - |
              bundle exec rails db:migrate
          envFrom:
            - configMapRef:
                name: config
          volumeMounts:
            - mountPath: /mastodon/public/system
              name: web-sidekiq
      containers:
        - name: sidekiq
          image: tootsuite/mastodon:v4.2.10
          resources:
            requests:
              memory: "768M"
          args:
            - bundle
            - exec
            - sidekiq
            - -c
            - "20"
          envFrom:
            - configMapRef:
                name: config
          volumeMounts:
          - mountPath: /mastodon/public/system
            name: web-sidekiq
      volumes:
      - name: web-sidekiq
        persistentVolumeClaim:
          claimName: web-sidekiq-pvc
