kind: ConfigMap
apiVersion: v1
metadata:
  name: env
  namespace: mastodon
data:
  REDIS_HOST: "redis.kubedb.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: ""
  DB_HOST: "main-rw.cnpg-system.svc.cluster.local"
  DB_USER: "mastodon"
  DB_NAME: "mastodon"
  DB_PASS: ""
  DB_PORT: "5432"
  LOCAL_DOMAIN: "mastodon.yude.jp.eu.org"
  SECRET_KEY_BASE: ""
  OTP_SECRET: ""
  VAPID_PRIVATE_KEY: ""
  VAPID_PUBLIC_KEY: ""
  SINGLE_USER_MODE: "false"
  DEFAULT_LOCALE: "ja"
  SMTP_SERVER: "yudejp.sakura.ne.jp"
  SMTP_PORT: "587"
  SMTP_LOGIN: ""
  SMTP_PASSWORD: ""
  SMTP_FROM_ADDRESS: "noreply@yude.jp"
  S3_ENABLED: "true"
  S3_BUCKET: "mastodon"
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  S3_ALIAS_HOST: "minio.yude.jp.eu.org/mastodon.yude.jp.eu.org"
  S3_REGION: "ap-northeast-1"
  S3_PROTOCOL: "https"
  S3_HOSTNAME: "minio.yude.jp.eu.org"
  S3_ENDPOINT: "https://minio.yude.jp.eu.org"
  PREPARED_STATEMENTS: "true"
  STREAMING_CLUSTER_NUM: "1"
