apiVersion: batch/v1
kind: Job
metadata:
  name: migration
  namespace: mastodon
spec:
  template:
    spec:
      containers:
        - name: db-migrate
          image: tootsuite/mastodon:v4.2.10
          command: ["bash", "-c", "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails db:migrate"]
          envFrom:
            - configMapRef:
                name: env
      restartPolicy: OnFailure
