apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyberchef
spec:
  selector:
    matchLabels:
      app: cyberchef
  replicas: 3
  template:
    metadata:
      labels:
        app: cyberchef
    spec:
      containers:
      - name: cyberchef
        image: mpepping/cyberchef:latest
        ports:
        - containerPort: 8000