---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyberchef
spec:
  selector:
    matchLabels:
      app: cyberchef
  replicas: 3
  template:
    metadata:
      labels:
        app: cyberchef
    spec:
      containers:
      - name: cyberchef
        image: mpepping/cyberchef:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: cyberchef
spec:
  selector:
    app: cyberchef
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000