apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  grafana.ini: |
    [log]
    ; # Either "debug", "info", "warn", "error", "critical", default is "info"
    ; # we change from info to debug level
    level = debug

    [database]
    type = postgres
    host = za-pg-16.default.svc.cluster.local
    name = grafana
    user = postgres
    password = cWF6z9DNxDj2XT3K7hCd7OhN7B4MQbYuVooswJcRPFLV9LiSOwtFUm2ECVLEtaiH
    ssl_mode = disable

    [auth.anonymous]
    enabled = true
    org_name = Public
    org_role = Viewer
    hide_version = true
