apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  grafana.ini: |
    [log]
    ; # Either "debug", "info", "warn", "error", "critical", default is "info"
    ; # we change from info to debug level
    level = debug

    [database]
    type = postgres
    host = main-rw.cnpg-system.svc.cluster.local
    name = grafana
    user = grafana
    password = kOdbVACxM4PJIm
    ssl_mode = disable

    [auth.anonymous]
    enabled = true
    org_name = Public
    org_role = Viewer
    hide_version = true