kind: ConfigMap
apiVersion: v1
metadata:
  name: lam-env
data:
  LAM_SKIP_PRECONFIGURE: "false"
  LDAP_DOMAIN: soine.site
  LDAP_BASE_DN: dc=soine,dc=site
  LDAP_USERS_DN: ou=people,dc=soine,dc=site
  LDAP_GROUPS_DN: ou=groups,dc=soine,dc=site
  LDAP_SERVER: ldap://192.0.2.1:389
  LDAP_USER: cn=foo,dc=soine,dc=site
  LAM_LANG: ja_JP
  LAM_PASSWORD: lam
  LAM_CONFIGURE_CRON: "false"
  LAM_CONFIGURATION_DATABASE: files
  LAM_DISABLE_TLS_CHECK: "true"
