---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: excalidraw
  name: excalidraw
spec:
  ports:
  - name: "8004"
    port: 8004
    targetPort: 8004
  selector:
    app: excalidraw
