apiVersion: apps/v1
kind: Deployment
metadata:
  name: www
  labels:
    app: www
spec:
  replicas: 3
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
        - name: www
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-html-volume
          configMap:
            name: nginx-html-config