apiVersion: kubedb.com/v1
kind: Redis
metadata:
  name: redis
  namespace: kubedb
spec:
  version: 7.4.0
  replicas: 3
  sentinelRef:
    name: sentinel
    namespace: kubedb
  mode: Sentinel
  storage:
    resources:
      requests:
        storage: 3Gi
    storageClassName: "local-path"
    accessModes:
      - ReadWriteOnce
  deletionPolicy: Halt