apiVersion: kubedb.com/v1
kind: RedisSentinel
metadata:
  name: sentinel
  namespace: kubedb
spec:
  version: 7.4.0
  replicas: 3
  storageType: Durable
  storage:
    resources:
      requests:
        storage: 3Gi
    storageClassName: "local-path"
    accessModes:
    - ReadWriteOnce
  deletionPolicy: WipeOut