apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pma
  name: pma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pma
  # strategy:
  #   type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pma
    spec:
      containers:
      - image: phpmyadmin/phpmyadmin
        name: phpmyadmin
        ports:
        - containerPort: 80
        env:
        - name: PMA_ABSOLUTE_URI
          value: "https://phpmyadmin.yude.jp.eu.org"
        - name: PMA_HOST
          value: galera-mariadb-galera.default.svc.cluster.local
        - name: PMA_PORT
          value: "3306"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: galera-mariadb-galera
              key: mariadb-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: pma-service
spec:
  type: ClusterIP
  selector:
    app: pma
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80