apiVersion: v1
kind: Secret
metadata:
  name: storage-configuration
  namespace: minio-tenant
stringData:
  config.env: |-
    export MINIO_ROOT_USER="admin"
    export MINIO_ROOT_PASSWORD="piyo"
    export MINIO_STORAGE_CLASS_STANDARD="EC:2"
    export MINIO_BROWSER="on"
type: Opaque
---
apiVersion: v1
data: # should be base64 encoded string
  CONSOLE_ACCESS_KEY: piyo
  CONSOLE_SECRET_KEY: fuga
kind: Secret
metadata:
  name: storage-user
  namespace: minio-tenant
type: Opaque